[colors.bright]
black = "#727072"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[colors.normal]
black = "#403E41"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[colors.primary]
background = "#ffffff"
foreground = "#22476b"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "CaskaydiaCove NF"
style = "Regular"

[window.dimensions]
columns = 95
lines = 26
