[v1]
"bacon 2.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"bob-nvim 2.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bob"]
"cargo-bloat 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-expand 1.0.70 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-msrv 0.15.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-msrv"]
"cargo-update 13.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cxp 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cxp"]
"datafusion-cli 31.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["datafusion-cli"]
"du-dust 0.8.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"just 1.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"ouch 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["ouch"]
"pqrs 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["pqrs"]
"pup 0.1.1 (git+https://github.com/SteveLauC/pup#f2238677594fdd58281947abbcc4df82008bf9cf)" = ["pup"]
"starship 1.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"topgrade 12.0.2 (git+https://github.com/topgrade-rs/topgrade#4dd1c13bd8065dfd791cb31e282c7c384dfff008)" = ["topgrade"]
