[v1]
"bacon 2.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"bob-nvim 2.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bob"]
"cargo-msrv 0.15.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-msrv"]
"cargo-update 13.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cxp 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cxp"]
"datafusion-cli 30.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["datafusion-cli"]
"du-dust 0.8.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"ouch 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["ouch"]
"pup 0.1.1 (git+https://github.com/SteveLauC/pup#f2238677594fdd58281947abbcc4df82008bf9cf)" = ["pup"]
"starship 1.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"topgrade 12.0.2 (git+https://github.com/topgrade-rs/topgrade#ce234bdb59525cc99dbdaadb1bf73cc009cb7a27)" = ["topgrade"]
