theme = "ayu_light"

[editor]
auto-save = false
line-number = "relative"
mouse = true
bufferline = "multiple"
shell = ["zsh", "-c"]

[editor.statusline]
left = ["mode", "spinner", "file-name", "position", "position-percentage" ,"spacer", "spacer", "diagnostics"] 
center = []
right = []


[editor.cursor-shape]
insert = "bar"
