[[language]]
name = "markdown"
# This tab-width does not seem to work at all.
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
# This tab-width does not seem to work at all.
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
auto-format = true
