[misc]
assume_yes = true
disable = ["pip3", "gnome_shell_extensions", "node", "rustup", "containers", "firmware"]
pre_sudo = true

[git]
pull_predefined = false
pull_only_repos = [
    "~/Documents/Notes",
    "~/Documents/dotfiles",
]
