[misc]
assume_yes = true
disable = ["pip3", "gnome_shell_extensions", "node", "rustup"]
pre_sudo = true


[git]
pull_predefined = false
repos = [
    "~/Documents/Notes",
    "~/Documents/dotfiles",
]
